---
PORTS_VLANS:
  
  Management:
    ge-0/0/0: POS0
    ge-0/0/1: POS1
    ge-0/0/2: POS2
    ge-0/0/3: POS3
    ge-0/0/4: POS4
    ge-0/0/5: POS5
    ge-0/0/6: POS6
    ge-0/0/7: POS7
    ge-0/0/8: POS8
    ge-0/0/9: POS9
    ge-0/0/10: POS10
    ge-0/0/11: POS11
    ge-0/0/12: POS12
    ge-0/0/13: POS13
    ge-0/0/14: POS14 - KSD11
    ge-0/0/15: KDS10
    ge-0/0/15: KDS10
    ge-0/0/16: KDS1
    ge-0/0/17: KDS2
    ge-0/0/18: KDS3
    ge-0/0/19: KDS4
    ge-0/0/20: KDS5
    ge-0/0/21: KDS6
    ge-0/0/22: KDS7
    ge-0/0/23: KDS8
    ge-0/0/24: KDS9
    ge-0/0/25: Kitchen Recipe 1
    ge-0/0/26: Kitchen Recipe 2
    ge-0/0/30: Westec
    ge-0/0/31: Westec
    ge-0/0/32: BOS
    ge-0/0/33: unknown
    ge-0/0/36: IPOffice-VOIP
    ge-0/0/37: Muisc System
    ge-0/0/38: Office Printer
    ge-0/0/39: Equinox
    ge-0/0/40: DASH Server
      
  HVAC:
    ge-0/0/27: HVAC1
    ge-0/0/28: HVAC2
    ge-0/0/29: HVAC3
    
  QSR:
    ge-0/0/34: QSR
    ge-0/0/35: QSR    
  
PORTS_WIFI_AP:
  ge-0/0/41: AP1
  ge-0/0/42: AP2
  ge-0/0/43: AP3
  ge-0/0/44: AP4
  ge-0/0/45: AP5
#  ge-0/0/46: AP6
#  ge-0/0/47: AP7
  
PORTS_UPLINK:
  ge-0/0/46: UPLINK_1
  ge-0/0/47: UPLINK_2
#  ge-0/1/0: UPLINK_1
#  ge-0/1/1: UPLINK_2
  
  
  
  
  
