---
- hosts: yocow_foh
  connection: local
  gather_facts: False
  roles:
    - shared
    - yocow_shared
    - yocow_foh
  tasks:
    - include: tasks/config_builder.yml YOID_brand=yocow YOID_role=foh
