---
- hosts: "{{ hosts }}"
  connection: local
  gather_facts: False
  vars_files:
    - "{{ target_ipaddrs }}"
 
  tasks:
  - name: "Obtaining inventory_host target IP address"
    set_fact: target_ipaddr="{{ TARGET_IPADDRS[ inventory_hostname ] }}"
    
  - name: "Installing Complete Junos configuration"
    action: junos_install_config
    args:
      invhostname: "{{ inventory_hostname }}"
      target: "{{ target_ipaddr }}"
      filename: junos.conf
      dir: "/var/tmp/{{ inventory_hostname }}"
      override: True      
    

